---
general:
  buildTool: "mta"

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "Sistemas_Globales_S.A_Globant"
    cfSpace: "DEV"
    cfAppName: "app"
    cfCredentialsId: "deploy-to-cf"
    uiVeri5ExecuteTests: false

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "Sistemas_Globales_S.A_Globant"
    cfSpace: "DEV"
    cfAppName: "app"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: true

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  npmExecuteLint:
    failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  tmsUpload:
    nodeName: "qas"
    credentialsId: "tms-sk"
    #Comit para darle seguimiento